// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import {Ownable} from "@openzeppelin/contracts/access/Ownable.sol";
import {Pausable} from "@openzeppelin/contracts/utils/Pausable.sol";
import {ReentrancyGuard} from "@openzeppelin/contracts/utils/ReentrancyGuard.sol";

/// @title EmbeddedMiniappTreasury
/// @notice Embedded treasury contract for collecting entry fees and admin-only withdrawals.
/// @dev Designed for Base (EVM).
contract EmbeddedMiniappTreasury is Ownable, Pausable, ReentrancyGuard {
    /// @notice Emitted when an entry fee is deposited.
    /// @param from Payer
    /// @param amount Amount of ETH deposited
    /// @param matchId Backend-provided id (bytes32) to correlate deposits
    event EntryFeeReceived(address indexed from, uint256 amount, bytes32 indexed matchId);

    /// @notice Emitted when funds are withdrawn from the treasury.
    /// @param to Receiver
    /// @param amount Amount of ETH withdrawn
    event TreasuryWithdrawal(address indexed to, uint256 amount);

    /// @notice Emitted when plain ETH is received with no matchId.
    /// @param from Sender
    /// @param amount Amount of ETH received
    event Received(address indexed from, uint256 amount);

    constructor(address initialOwner) Ownable(initialOwner) {}

    /// @notice Accept plain ETH transfers.
    receive() external payable whenNotPaused {
        emit Received(msg.sender, msg.value);
    }

    /// @notice Deposit an entry fee (ETH) with an optional matchId.
    /// @dev matchId generated by backend.
    function depositEntryFee(bytes32 matchId) external payable whenNotPaused {
        require(msg.value > 0, "No value");
        emit EntryFeeReceived(msg.sender, msg.value, matchId);
    }

    /// @notice Withdraw ETH from the treasury (admin-only).
    /// @dev Use for end of season distribution operations.
    function withdraw(address payable to, uint256 amount) external onlyOwner nonReentrant {
        require(to != address(0), "Bad to");
        require(amount <= address(this).balance, "Insufficient");
        (bool ok, ) = to.call{value: amount}("");
        require(ok, "Transfer failed");
        emit TreasuryWithdrawal(to, amount);
    }

    /// @notice Pause deposits (admin-only).
    function pause() external onlyOwner {
        _pause();
    }

    /// @notice Unpause deposits (admin-only).
    function unpause() external onlyOwner {
        _unpause();
    }

    /// @notice Current contract ETH balance.
    function balance() external view returns (uint256) {
        return address(this).balance;
    }
}
